# Generated by Django 3.1.5 on 2021-01-21 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=200, unique=True)),
                ('e_mail', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('age', models.IntegerField()),
                ('createdat', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
