# Generated by Django 3.1.5 on 2021-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcinephile', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.ImageField(default='default_m.jpg', upload_to='poster_pic'),
        ),
    ]
