# Generated by Django 3.1.5 on 2021-04-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcinephile', '0006_auto_20210311_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(blank=True, max_length=100)),
                ('pen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcinephile.profile')),
            ],
        ),
    ]
