# Generated by Django 3.1.5 on 2021-04-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcinephile', '0007_watched_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='watched_list',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watched_list',
            name='poster',
            field=models.ImageField(default='default_m.jpg', upload_to='poster_pic'),
        ),
    ]
